// POSTS
export const GET_FOLLOWINGS_USER_POSTS_START = 'GET_FOLLOWINGS_USER_POSTS_START';
export const GET_FOLLOWINGS_USER_POSTS_SUCCESS = 'GET_FOLLOWINGS_USER_POSTS_SUCCESS';
export const GET_FOLLOWINGS_USER_POSTS_FAILED = 'GET_FOLLOWINGS_USER_POSTS_FAILED';

// LOCAL POSTS
export const GET_LOCAL_POSTS_START = 'GET_LOCAL_POSTS_START';
export const GET_LOCAL_POSTS_SUCCESS = 'GET_LOCAL_POSTS_SUCCESS';
export const GET_LOCAL_POSTS_FAILED = 'GET_LOCAL_POSTS_FAILED';
