// UPLOAD POST
export const UPLOAD_POST_START = 'UPLOAD_POST_START';
export const UPLOAD_POST_SUCCESS = 'UPLOAD_POST_SUCCESS';
export const UPLOAD_POST_FAILED = 'UPLOAD_POST_FAILED';
//

// POSTS
export const RESET_POSTS = 'RESET_POSTS';
export const GET_MY_POSTS_START = 'GET_MY_POSTS_START';
export const GET_MY_POSTS_SUCCESS = 'GET_MY_POSTS_SUCCESS';
export const GET_MY_POSTS_FAILED = 'GET_MY_POSTS_FAILED';
//

// POSTS
export const GET_FOLLOWINGS_USER_POSTS_START = 'GET_FOLLOWINGS_USER_POSTS_START';
export const GET_FOLLOWINGS_USER_POSTS_SUCCESS = 'GET_FOLLOWINGS_USER_POSTS_SUCCESS';
export const GET_FOLLOWINGS_USER_POSTS_FAILED = 'GET_FOLLOWINGS_USER_POSTS_FAILED';

// LOCAL POSTS
export const GET_LOCAL_POSTS_START = 'GET_LOCAL_POSTS_START';
export const GET_LOCAL_POSTS_SUCCESS = 'GET_LOCAL_POSTS_SUCCESS';
export const GET_LOCAL_POSTS_FAILED = 'GET_LOCAL_POSTS_FAILED';

// SAVED POSTS
export const GET_SAVED_POSTS_START = 'GET_SAVED_POSTS_START';
export const GET_SAVED_POSTS_SUCCESS = 'GET_SAVED_POSTS_SUCCESS';
export const GET_SAVED_POSTS_FAILED = 'GET_SAVED_POSTS_FAILED';