// POSTS
export const GET_FOLLOWINGS_USER_POSTS_START = 'GET_FOLLOWINGS_USER_POSTS_START';
export const GET_FOLLOWINGS_USER_POSTS_SUCCESS = 'GET_FOLLOWINGS_USER_POSTS_SUCCESS';
export const GET_FOLLOWINGS_USER_POSTS_FAILED = 'GET_FOLLOWINGS_USER_POSTS_FAILED';

// HOME POSTS TAB
export const SET_INITIAL_PAGE = 'SET_INITIAL_PAGE';