// FOLLOW - UNFOLLOW
export const FOLLOW_USER_START = 'FOLLOW_USER_START';
export const FOLLOW_USER_SUCCESS = 'FOLLOW_USER_SUCCESS';
export const FOLLOW_USER_FAILED = 'FOLLOW_USER_FAILED';
export const UNFOLLOW_USER_START = 'UNFOLLOW_USER_START';
export const UNFOLLOW_USER_SUCCESS = 'UNFOLLOW_USER_SUCCESS';
export const UNFOLLOW_USER_FAILED = 'UNFOLLOW_USER_FAILED';
//

// FOLLOWERS - FOLLOWINGS
export const GET_FOLLOWERS_START = 'GET_FOLLOWERS_START';
export const GET_FOLLOWERS_SUCCESS = 'GET_FOLLOWERS_SUCCESS';
export const GET_FOLLOWERS_FAILED = 'GET_FOLLOWERS_FAILED';
export const GET_FOLLOWINGS_START = 'GET_FOLLOWINGS_START';
export const GET_FOLLOWINGS_SUCCESS = 'GET_FOLLOWINGS_SUCCESS';
export const GET_FOLLOWINGS_FAILED = 'GET_FOLLOWINGS_FAILED';
export const SET_FOLLOWINGS = 'SET_FOLLOWINGS';
//

// SUGGESTIONS
export const GET_MOST_FOLLOWED_USERS_START = 'GET_MOST_FOLLOWED_USERS_START';
export const GET_MOST_FOLLOWED_USERS_SUCCESS = 'GET_MOST_FOLLOWED_USERS_SUCCESS';
export const GET_MOST_FOLLOWED_USERS_FAILED = 'GET_MOST_FOLLOWED_USERS_FAILED';

export const RESET_FOLLOWINGS_AND_FOLLOWERS = 'RESET_FOLLOWINGS_AND_FOLLOWERS';